import type { Metadata } from "next";
import "./../globals.css";
import PagesLayout from "./PagesLayout";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <PagesLayout>{children}</PagesLayout>
  );
}
