[[plugins]]
package = "@netlify/plugin-nextjs"
[[headers]]
  for = "/api/products/selectedProducts/*"
  [headers.values]
    "Cache-Control" = "private, no-cache, no-store, must-revalidate"
    "Pragma" = "no-cache"
    "Expires" = "0"
    "Vary" = "*"
    "Netlify-CDN-Cache-Control" = "private, no-cache, no-store, must-revalidate"