import type { Metadata } from "next";
import "../../../app/globals.css";
import SingleProductLayout from "@/app/_components/singleProductLayout/SingleProductLayout";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <SingleProductLayout>{children}</SingleProductLayout>
  );
}
