import { NextRequest, NextResponse } from "next/server";
import { generateProductDetails } from "./generateProductDetails";
export async function POST(request: NextRequest) {
    try {
        const body = await request.json() as { productTitle?: string };
        const { productTitle } = body;
        console.log("Received productTitle:", productTitle);
        if (!productTitle) {
            return NextResponse.json(
                { message: "Product Title is not defined", success: false, status: 400 },
                { status: 400 }
            );
        }
        const productDetails = await generateProductDetails(productTitle);
        return NextResponse.json({
            message: "Product Details Generated by AI",
            success: true,
            status: 200,
            data: productDetails,
        });
    } catch (error: any) {
        console.error("Error generating product details:", error);
        return NextResponse.json(
            { message: "Internal Server Error", success: false, status: 500 },
            { status: 500 }
        );
    }
}
