import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import QueryProvider from "./provider/queryProvider";
const myFont = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--myFont",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Ecommerce KTM - One Stock Electronics Store in Kathmandu , Nepal",
  description: "Generated by create next app",
  keywords:['online shopping nepal','ecommerce ktm','buy  in kathmandu'],
  alternates:{
    canonical:"https://ecommercektm.vercel.app"
  }
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.variable}`}
      >
        <QueryProvider>
        {children}
        </QueryProvider>
      </body>
    </html>
  );
}
