import type { Metadata } from "next";
import "./../globals.css";
import DashboardLayout from "./DashboardLayout";
import DashboardSidebar from "./DashboardSidebar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <DashboardLayout>
          <div className="dashboard flex container my-4">
            <DashboardSidebar/>
              {children}
          </div>
          </DashboardLayout>
  );
}
