import type { Metadata } from "next";
import "@/app/globals.css";
import { UserDetailsContext, UserDetailsContextComponent } from "@/app/context/UserDetailsContextComponent";
import AdvanceSearchProvider from "@/app/_components/advaceSearch/AdvanceSearchProvider";
import NavBar from "@/app/_components/navbar/Navbar";
import Footer from "@/app/_components/footer/Footer";
import { useContext } from "react";
import { Provider } from "react-redux";
import store from "@/app/redux/store";
import QueryProvider from "@/app/provider/queryProvider";
import CatalogPageLayout from "./CatalogPageLayout";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <>
       <CatalogPageLayout>
        {children}
       </CatalogPageLayout>
        </>
  );
}
