import type { Metadata } from "next";
import "@/app/globals.css";
import { UserDetailsContext, UserDetailsContextComponent } from "@/app/context/UserDetailsContextComponent";
import AdvanceSearchProvider from "@/app/_components/advaceSearch/AdvanceSearchProvider";
import NavBar from "@/app/_components/navbar/Navbar";
import Footer from "@/app/_components/footer/Footer";
import { useContext } from "react";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const context = useContext(UserDetailsContext);
    if(!context){
      throw new Error("The User Details context is not working.")
    }
    const {userDetails} = context;
  return (
        <>
         <AdvanceSearchProvider>
            <UserDetailsContextComponent>
         <NavBar/>
         {children}
         <Footer/>
         </UserDetailsContextComponent>
         </AdvanceSearchProvider>
        </>
  );
}
